# Generated by Django 2.1.3 on 2021-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategorieId', models.AutoField(primary_key=True, serialize=False)),
                ('CategorieName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('RefCategorie', models.CharField(max_length=500)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductDecrip', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
